### ISSUE TITLE
PDFs don't work

### ISSUE THREAD

**Issue by oliversauter** [WebMemex/freeze-dry#12]
PDFs are currently not archived. 

<img width="1680" alt="screen shot 2017-07-21 at 18 02 12" src="https://user-images.githubusercontent.com/7870039/28471835-be1113b4-6e3e-11e7-8f85-dad49773222a.png">

**Comment by Treora** [comment]
Correct. This is out of scope for freeze-dry, but I added the issue here: https://github.com/WebMemex/webmemex-extension/issues/118
