### ISSUE TITLE
Keep 'media' attribute of stylesheets (was: Rendering Error on Guardian pages)

### ISSUE THREAD

**Issue by oliversauter** [WebMemex/freeze-dry#14]
On guardian pages, the freeze dry version looks like this: 

![screen shot 2017-07-31 at 10 31 26](https://user-images.githubusercontent.com/7870039/28769361-7b2cb25c-75db-11e7-8af6-51515adbc471.png)

And this is the console log:
![screen shot 2017-07-31 at 10 33 58](https://user-images.githubusercontent.com/7870039/28769434-cad67ce8-75db-11e7-9f8e-3de6c4690198.png)

**Comment by Treora** [comment]
Thanks for reporting; the messages in the console are expected; we do not yet inline `<iframe>`s (#3) or `<source>` elements (#4). However I do not yet see why the stylesheet is not being applied, which breaks the whole look..

**Comment by Treora** [comment]
Ah now I see. A `<link rel="stylesheet" media='print'>` is simply inlined as a `<style>` element, so the page is styled for printing. We should keep the `media` attribute (and perhaps others) when converting `<link>` to `<style>`.

**Comment by Treora** [comment]
Fixed in commit da6fc31. We now do not replace a `link` with a `style` element anymore, but just modify its `href` attribute (inlining the stylesheet as a data URL). Attributes such as `media` thus remain in place, so we can finally read the Guardian again.
