### ISSUE TITLE
Upstream freeze-dry dependency doesn't work with yarn

### ISSUE THREAD

**Issue by pvh** [WebMemex/freeze-dry#34]
We get this error message: 
```
$ capstone [master ≡ +0 ~4 -0 !]> yarn
yarn install v1.10.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error mutable-proxy@0.1.7: The engine "node" is incompatible with this module. Expected version "6.X.X". Got "8.9.0"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

The workaround is to run yarn with `--ignore-engines`, but it's sort of a pain.

**Comment by Treora** [comment]
Sorry about that. I reported this before at https://github.com/Griffingj/mutable-proxy/pull/1, but no response there so far. If needed we could drop or fork the dependency; I just asked there for its author's opinion.

**Comment by Treora** [comment]
Fixed in commit e0a4201, sorry for the delay.

**Comment by pvh** [comment]
No worries! Thanks for following up.

**Comment by dpffxhad** [comment]
@Treora I still have error installing with yarn.

**Comment by Treora** [comment]
I assume that is because I forgot to publish the package after the changes.. done now (version 0.2.2), thanks for reminding!
