### ISSUE TITLE
Could you please publish used deps onto git as well

### ISSUE THREAD

**Issue by Gozala** [WebMemex/freeze-dry#36]
I would really like to use this with plain ESM &  without build steps. Other than #35 I also run into issue that some of the dependencies used aren't published in non compiled form anywhere. @Treora Given that you're the author of some of those deps would you mind publishing them to github as well ?

Thanks

**Comment by Treora** [comment]
I assume you mean document-outerhtml and its dependency doctype-to-string. I see I forgot to publish my updated package.json files that link to the repositories. The sources are published, using git, but not git*hub*:
- [document-outerhtml](https://code.treora.com/gerben/document-outerhtml)
- [doctype-to-string](https://code.treora.com/gerben/doctype-to-string)

I try to host new projects I create myself, to slowly escape from the github singleton. Unfortunately my gitea instance is still a half-baked solution, as people cannot even create issues or pull requests there.. (back to old-fashioned emails with patches‽ I'd like to try fix the third-party auth some day, or even better, help get these features to federate)

Let know if this might solve your problem already.

**Comment by Gozala** [comment]
You might want to look at git-ssb https://git.scuttlebot.io/%25n92DiQh7ietE%2BR%2BX%2FI403LQoyf2DtR3WQfCkDKlheQU%3D.sha256

**Comment by Treora** [comment]
Assuming this as being resolved; let know if my gitea instance does not suffice. I just tweaked it to enable visitors to log in with some third-party identity providers there, so you should at least be able to open issues there (support for federated pull requests may have to wait..).

And git-ssb may be worth a try indeed!
