### ISSUE TITLE
How to use in browser

### ISSUE THREAD

**Issue by dvn0** [WebMemex/freeze-dry#47]
I'm having some trouble figuring out how to use this library in the browser. I've taken a look at the way you use it in `webmemex-extension`, and I'm struggling to figure out a way to use freeze-dry ad-hoc through the browser console.

Any thoughts?

**Comment by dvn0** [comment]
cc @Treora

**Comment by Treora** [comment]
One somewhat classical approach, using browserify:

Step 0: of course, first run `npm install`, which should invoke 'prepare' script which transpiles the source into the `lib` folder)

Step 1: Create a standalone bundle: `browserify --standalone freezeDry -o standalone.js lib/index.js`

This gives a file `standalone.js` that you can host somewhere. You could also skip the above steps and get it from the wzrd.in browserify-as-a-service: `https://wzrd.in/standalone/freeze-dry`

Step 2: Add the script to the page you want to freeze-dry. In the browser console:

    e = document.createElement('script')
    e.src = 'https://wzrd.in/standalone/freeze-dry'
    document.head.appendChild(e)

Step 3: The module should now be a global variable `freezeDry`; hence the function to use is `freezeDry.default()`:

    html = await freezeDry.default()

This method however feels pretty old-fashioned, I hope we could just run something like `import freezeDry from "https://......./freezeDry". We’d need to bundle/package things a bit differently; browserify appears unfit for this. I’d be happy to hear a (convenient) solution!

**Comment by dvn0** [comment]
That solution works great for me in the web console. Thanks a lot! I wasn't so far off: I was trying to use `freezeDry()` instead of `freezeDry.default()`. Now it makes good sense to me though.

I agree it would be nice to figure out a way to to run as an import like you suggested. For now I will try to make do with this. My next task which I have yet to succeed at is running the equivalent of this from a script instead of manually inputting into the web console line-by-line.

I thought it would be quite simple using the code you have here, but I keep stumbling over issues with scoping and async.

**Comment by dvn0** [comment]
Ended up figuring it out! Await/async is good fun. ;)
