### ISSUE TITLE
freeze drying twitter seems to produce unreadable results.

### ISSUE THREAD

**Issue by Gozala** [WebMemex/freeze-dry#50]
So far I was not very successful in figuring the root cause.

**Comment by Treora** [comment]
Can reproduce indeed. It appears to be the dynamic CSS issue (#45) you just commented on: the content of the second `<style>` tag does not reflect its value in the DOM. (I still wonder why the DOM does not just update to reflect such changes..) I could fix a snapshot by manually editing its HTML and replacing the <style> contents with the output of running this in the browser console on the original page:

```
Array.from(document.styleSheets[1].cssRules).map(rule => rule.cssText).join('\n')
```

Will close this issue as a duplicate.

**Comment by Gozala** [comment]
Hmm I was suspecting it, but doing exactly what you suggested did not seem to do the trick. Maybe I made some mistake while doing so. Glad it's the same issue.
