### ISSUE TITLE
Stop adding <base href>, always rewrite relative URLs

### ISSUE THREAD

**Issue by Treora** [WebMemex/freeze-dry#6]
Unfortunately a `<base href='...'>` is also applied on relative links *within* a document, e.g. `href="#section3"`. It would be nice to keep those internal links relative. Rewriting relative `href`s rather than using a `base` element seems the easiest (only?) solution.

**Comment by erikrose** [comment]
If we do rewrite them, let's at least preserve the original data somewhere (like in a data attr), for tools like Fathom which may examine such things.
