### ISSUE TITLE
Provide the option to get resources separately.

### ISSUE THREAD

**Issue by Treora** [WebMemex/freeze-dry#8]
Instead of inlining everything, we could offer to return the resources separately. The application can then store it in whichever way it likes, and could provide the URL to replace the original URL with.

Particularly useful for deduplicating the resources, possibly using a content-addressing scheme.

**Comment by Treora** [comment]
Achieving this should be much easier now since v0.2.0. Only the last step ([src/createSingleFile.js](https://github.com/WebMemex/freeze-dry/blob/afb24d5de33c909610927fd738c73dde9a248cc6/src/create-single-file.js)) would have to be modified.

**Comment by Gozala** [comment]
I would really like to use this feature! Maybe an option could be added like `saveResource(url, content):Promise<?URL>` which would save and return URL for the saved resource or return `null` if resource should be just ignored.

**Comment by Gozala** [comment]
I've made a small change https://github.com/Gozala/freeze-dry/commit/161c4fe8e108df5fd2bedb18ce4c5474404ef0dc that introduces `blobToURL` option (with default `blobToDataURL` that is just used in place of `blobToDataURL`. With this change current behavior is default but `blobToURL` can be passed to use alternative resource storing mechanism.

**Comment by Gozala** [comment]
I can decouple it from unrelated changes and submit pull request if there's interest.

**Comment by Treora** [comment]
In your approach, I like the elegance of just replacing `blobToUrl`. We could pass it a few more arguments (e.g. the original URL, or the whole `link.resource` or `link` object), so that a custom implementation could make use of that when creating the replacement URL. And of course we would accordingly rename it to `subresourceToUrl` or so.

For a user, just customising this `blobToUrl` would suffice to create some other output formats/actions, e.g. publishing each subresource on IPFS. However, some other formats would need a few more changes to this last step. For example for creating an MHTML or WARC file one would need to concatenate the files. In theory, for these one could construct a `blobToUrl` function that builds a list of strings and then concatenates the list items after freeze-dry returns; but perhaps it would be simpler to have freeze-dry return the `resource` tree, and let the caller decide what to do with this.

Could be worth to provide both options, for simple customisation or larger customisation. Or perhaps the fourth step of freeze-dry should be a separate function, so one can swap it out: 

    const resourceTree = freezeDry(document, captureOptions)
    // Use current implementation, if it were factored out.
    const html = createSingleFile(resourceTree, { blobToUrl: addToIPFS }
    const finalAddress = addToIPFS(html)
    // or replace the whole last step:
    const mhtml = toMHTML(resourceTree)

Thoughts welcome as always

**Comment by Gozala** [comment]
> In your approach, I like the elegance of just replacing blobToUrl. We could pass it a few more arguments (e.g. the original URL, or the whole link.resource or link object), so that a custom implementation could make use of that when creating the replacement URL. And of course we would accordingly rename it to subresourceToUrl or so.

👍I just wanted to keep changes minimal, but I agree that’s probably a better option

**Comment by Gozala** [comment]
> For a user, just customising this blobToUrl would suffice to create some other output formats/actions, e.g. publishing each subresource on IPFS. However, some other formats would need a few more changes to this last step. For example for creating an MHTML or WARC file one would need to concatenate the files. In theory, for these one could construct a blobToUrl function that builds a list of strings and then concatenates the list items after freeze-dry returns; 

I have being thinking about that too, but failed to come up with an API that I’d be satisfied with. Personally I like reducer style for accumultive tasks like this. e.g:

```js
freezeDry(doc, opts, async (acc, resource) => {...}, buffer)
```

That usually enables aggregating the into whatever you pass as `buffer`. However, here you also need to return substitution URL which this doesn’t quite fit. So I decided it was to leave this use case to rest until it comes up.


> but perhaps it would be simpler to have freeze-dry return the resource tree, and let the caller decide what to do with this.

There are few issues with that:

1. You end up needing to buffer everything in the memory and only precess afterwards. Ideally cases where writes can happen in the process of traversal should be allowed to do that.
2. It’s unclear how substitution is going to be dealt. Would you need to return a resource tree (or array) mapping ? If so I think it makes API dramatically more complex and easier to mess up. And like above simpler cases get taxed for supporting complex ones.
